#!/usr/bin/env python3
"""Generate EasyEDA Standard JSON sources for OpenRD PDB v0.1.

The generated files are intentionally simple EasyEDA Standard JSON files:
- one schematic drawing JSON
- one PCB JSON with board outline, pads, holes, labels, and main power tracks
- one ZIP containing both JSON files for import

Coordinates in the PCB JSON use EasyEDA Standard's 10 mil base unit.
"""

from __future__ import annotations

import csv
import json
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "easyeda_std"

MM_TO_EASY = 1.0 / 0.254
BOARD_MM = 95.0
ORIGIN = 100.0


class Ids:
    def __init__(self) -> None:
        self.value = 1

    def next(self) -> str:
        item = f"gge{self.value}"
        self.value += 1
        return item


ids = Ids()


def n(value: float) -> str:
    text = f"{value:.3f}"
    return text.rstrip("0").rstrip(".")


def u(mm: float) -> float:
    return mm * MM_TO_EASY


def xy(x_mm: float, y_mm: float) -> tuple[float, float]:
    """Convert left-bottom mm coordinates to EasyEDA canvas coordinates."""
    return ORIGIN + u(x_mm), ORIGIN + u(BOARD_MM - y_mm)


def points(coords: list[tuple[float, float]]) -> str:
    return " ".join(f"{n(x)} {n(y)}" for x, y in coords)


def track(layer: int, net: str, width_mm: float, coords_mm: list[tuple[float, float]]) -> str:
    pts = [xy(x, y) for x, y in coords_mm]
    return f"TRACK~{n(u(width_mm))}~{layer}~{net}~{points(pts)}~{ids.next()}"


def silk_line(coords_mm: list[tuple[float, float]], width_mm: float = 0.25) -> str:
    return track(3, "", width_mm, coords_mm)


def hole(ref: str, x_mm: float, y_mm: float, dia_mm: float = 3.2) -> str:
    x, y = xy(x_mm, y_mm)
    return f"HOLE~{n(x)}~{n(y)}~{n(u(dia_mm))}~{ids.next()}"


def pad(
    ref: str,
    number: str,
    net: str,
    x_mm: float,
    y_mm: float,
    w_mm: float,
    h_mm: float,
    drill_mm: float,
    shape: str = "ELLIPSE",
    rotation: float = 0.0,
) -> str:
    x, y = xy(x_mm, y_mm)
    hole_radius = drill_mm / 2.0
    return (
        f"PAD~{shape}~{n(x)}~{n(y)}~{n(u(w_mm))}~{n(u(h_mm))}~11~"
        f"{net}~{number}~{n(u(hole_radius))}~~{n(rotation)}~{ids.next()}"
    )


def text(label: str, x_mm: float, y_mm: float, size_mm: float = 1.8, layer: int = 3) -> str:
    x, y = xy(x_mm, y_mm)
    # EasyEDA stores text height as 10 mil units. Path can be left blank and
    # regenerated by the editor after import.
    return f"TEXT~L~{n(x)}~{n(y)}~0.8~0~none~{layer}~~{n(u(size_mm))}~{label}~~~{ids.next()}"


def rect_silk(x1: float, y1: float, x2: float, y2: float) -> list[str]:
    return [
        silk_line([(x1, y1), (x2, y1)]),
        silk_line([(x2, y1), (x2, y2)]),
        silk_line([(x2, y2), (x1, y2)]),
        silk_line([(x1, y2), (x1, y1)]),
    ]


def build_pcb() -> dict:
    shapes: list[str] = []

    # Board outline.
    shapes.append(track(10, "", 0.25, [(0, 0), (95, 0), (95, 95), (0, 95), (0, 0)]))

    # Chassis mounting holes.
    for ref, x, y in [
        ("H1", 5, 5),
        ("H2", 90, 5),
        ("H3", 5, 90),
        ("H4", 90, 90),
    ]:
        shapes.append(hole(ref, x, y))

    # LTC3780 module outline and mounting holes.
    shapes.extend(rect_silk(7, 17, 89, 69))
    for ref, x, y in [
        ("U1H1", 13, 24),
        ("U1H2", 83, 24),
        ("U1H3", 13, 62),
        ("U1H4", 83, 62),
    ]:
        shapes.append(hole(ref, x, y))

    # J1/J2 Deans T pigtail pads. Pin 1 is positive.
    shapes.append(pad("J1", "1", "BATT+", 14, 87, 7.0, 7.0, 3.2))
    shapes.append(pad("J1", "2", "GND", 14, 77, 7.0, 7.0, 3.2))
    shapes.append(pad("J2", "1", "BAT_SW_12V", 80, 87, 7.0, 7.0, 3.2))
    shapes.append(pad("J2", "2", "GND", 80, 77, 7.0, 7.0, 3.2))

    # Fuses and switch pads.
    shapes.append(pad("F1", "1", "BATT+", 29, 82, 5.5, 5.5, 2.2))
    shapes.append(pad("F1", "2", "BATT_FUSED", 39, 82, 5.5, 5.5, 2.2))
    shapes.append(pad("SW1", "1", "BATT_FUSED", 47, 82, 5.5, 5.5, 2.2))
    shapes.append(pad("SW1", "2", "BAT_SW_12V", 57, 82, 5.5, 5.5, 2.2))
    shapes.append(pad("F2", "1", "BAT_SW_12V", 13, 48, 5.0, 5.0, 2.0))
    shapes.append(pad("F2", "2", "DCDC_IN_12V", 23, 48, 5.0, 5.0, 2.0))

    # 5.08 mm 2-pin terminal style pads.
    def terminal_2p(ref: str, cx: float, cy: float, net1: str, net2: str) -> None:
        shapes.append(pad(ref, "1", net1, cx - 2.54, cy, 3.8, 3.8, 1.4, shape="RECT"))
        shapes.append(pad(ref, "2", net2, cx + 2.54, cy, 3.8, 3.8, 1.4, shape="RECT"))

    terminal_2p("J3", 17, 32, "DCDC_IN_12V", "GND")
    terminal_2p("J4", 56, 32, "RK_12V", "GND")
    terminal_2p("J5", 78, 32, "RK_12V", "GND")
    terminal_2p("J7", 36, 13, "5V_AUX", "GND")

    # J6 ADC/Test 2.54 mm header.
    for i, (net, xoff) in enumerate([("BATT_SENSE", -2.54), ("GND", 0), ("NC_REF", 2.54)], start=1):
        shapes.append(pad("J6", str(i), net, 18 + xoff, 13, 2.0, 2.0, 1.0))

    # Through-hole placeholders for R/C/LED/test pads.
    shapes.append(pad("R1", "1", "BATT+", 12, 20, 1.8, 1.8, 0.8))
    shapes.append(pad("R1", "2", "BATT_SENSE_RAW", 17, 20, 1.8, 1.8, 0.8))
    shapes.append(pad("R2", "1", "BATT_SENSE_RAW", 22, 20, 1.8, 1.8, 0.8))
    shapes.append(pad("R2", "2", "GND", 27, 20, 1.8, 1.8, 0.8))
    shapes.append(pad("R3", "1", "BATT_SENSE_RAW", 14, 17, 1.8, 1.8, 0.8))
    shapes.append(pad("R3", "2", "BATT_SENSE", 19, 17, 1.8, 1.8, 0.8))
    shapes.append(pad("LED1", "A", "LED1_A", 56, 13, 1.8, 1.8, 0.8))
    shapes.append(pad("LED1", "K", "GND", 60, 13, 1.8, 1.8, 0.8))
    shapes.append(pad("RLED", "1", "BAT_SW_12V", 54, 17, 1.8, 1.8, 0.8))
    shapes.append(pad("RLED", "2", "LED1_A", 59, 17, 1.8, 1.8, 0.8))

    for ref, net, x in [
        ("TP1", "BATT+", 66),
        ("TP2", "BAT_SW_12V", 70),
        ("TP3", "RK_12V", 74),
        ("TP4", "BATT_SENSE", 78),
        ("TP5", "GND", 82),
    ]:
        shapes.append(pad(ref, "1", net, x, 13, 1.8, 1.8, 0.8))

    # Main routed copper as wide tracks. These are deliberately conservative
    # placeholders; pour/refine in EasyEDA before ordering.
    shapes.append(track(1, "BATT+", 6.0, [(14, 87), (20, 87), (29, 82)]))
    shapes.append(track(1, "BATT_FUSED", 6.0, [(39, 82), (47, 82)]))
    shapes.append(track(1, "BAT_SW_12V", 6.0, [(57, 82), (70, 82), (80, 87)]))
    shapes.append(track(1, "GND", 6.0, [(14, 77), (30, 77), (55, 77), (80, 77)]))
    shapes.append(track(1, "BAT_SW_12V", 4.0, [(57, 82), (57, 70), (13, 48)]))
    shapes.append(track(1, "DCDC_IN_12V", 4.0, [(23, 48), (23, 40), (14.46, 32)]))
    shapes.append(track(1, "RK_12V", 4.0, [(53.46, 32), (65, 32), (75.46, 32)]))
    shapes.append(track(2, "GND", 4.0, [(19.54, 32), (40, 32), (58.54, 32), (80.54, 32)]))
    shapes.append(track(1, "BATT_SENSE", 0.35, [(19, 17), (15.46, 13)]))

    # Via stitching around main bus.
    for x in [24, 32, 40, 48, 62, 70]:
        px, py = xy(x, 77)
        shapes.append(f"VIA~{n(px)}~{n(py)}~{n(u(1.2))}~GND~{n(u(0.6 / 2))}~{ids.next()}")

    # Silk labels.
    for label, x, y in [
        ("OpenRD PDB v0.1", 37, 92),
        ("BATT IN 3S 12V", 5, 91),
        ("MOTOR OUT", 72, 91),
        ("F1 10A", 30, 88),
        ("SW MAIN", 47, 88),
        ("F2 RK", 9, 54),
        ("LTC3780 78x46", 32, 45),
        ("RK 12V OUT DC5525 CENTER POSITIVE", 45, 25),
        ("DO NOT CHARGE HERE", 42, 5),
        ("ADC", 12, 9),
        ("5V AUX", 32, 9),
        ("TP", 70, 9),
    ]:
        shapes.append(text(label, x, y, 1.8))

    return {
        "head": "3~1.11.3~",
        "canvas": "CA~2400~2400~#000000~yes~#FFFFFF~10~1200~1200~line~5~mil~9~45~visible~0.5",
        "shape": shapes,
        "systemColor": "#000000~#FFFFFF~#FFFFFF~#000000~#FFFFFF",
        "layers": [
            "1~TopLayer~#FF0000~true~true~true",
            "2~BottomLayer~#0000FF~true~false~true",
            "3~TopSilkLayer~#FFFF00~true~false~true",
            "4~BottomSilkLayer~#808000~true~false~true",
            "5~TopPasterLayer~#808080~false~false~false",
            "6~BottomPasterLayer~#800000~false~false~false",
            "7~TopSolderLayer~#800080~false~false~false",
            "8~BottomSolderLayer~#AA00FF~false~false~false",
            "9~Ratlines~#6464FF~false~false~true",
            "10~BoardOutline~#FF00FF~true~false~true",
            "11~Multi-Layer~#C0C0C0~true~false~true",
            "12~Document~#FFFFFF~true~false~true",
        ],
        "DRCRULE": {
            "trackWidth": 0.7,
            "track2Track": 0.7,
            "pad2Pad": 0.8,
            "track2Pad": 0.8,
            "hole2Hole": 1,
            "holeSize": 1.6,
        },
    }


def schematic_line(x1: float, y1: float, x2: float, y2: float) -> str:
    return f"W~{n(x1)} {n(y1)} {n(x2)} {n(y2)}~#008800~1~0~none~{ids.next()}"


def schematic_text(text_value: str, x: float, y: float, size: str = "9pt") -> str:
    return f"T~L~{n(x)}~{n(y)}~0~#0000FF~Arial~{size}~~~~comment~{text_value}~1~start~{ids.next()}"


def schematic_box(x: float, y: float, w: float, h: float, label: str) -> list[str]:
    return [
        f"R~{n(x)}~{n(y)}~0~0~{n(w)}~{n(h)}~#000000~1~0~none~{ids.next()}",
        schematic_text(label, x + 8, y + 18),
    ]


def build_schematic() -> dict:
    shapes: list[str] = []
    shapes.append(schematic_text("OpenRD Power Distribution Board v0.1", 80, 60, "12pt"))
    shapes.append(schematic_text("Schematic source for EasyEDA Standard import", 80, 82, "9pt"))

    blocks = [
        (80, 160, 110, 50, "J1 BATT_IN"),
        (240, 160, 80, 50, "F1 10A"),
        (370, 160, 100, 50, "SW1 MAIN"),
        (530, 120, 120, 50, "J2 MOTOR_OUT"),
        (530, 230, 100, 50, "F2 RK"),
        (690, 230, 130, 50, "J3 DCDC_IN"),
        (850, 210, 150, 90, "U1 LTC3780"),
        (1060, 230, 130, 50, "J4 DCDC_OUT"),
        (1230, 230, 120, 50, "J5 RK_OUT"),
        (530, 360, 190, 70, "R1/R2/R3 SENSE"),
        (790, 360, 120, 70, "J6 ADC_TEST"),
        (990, 360, 120, 70, "LED1/RLED"),
    ]
    for block in blocks:
        shapes.extend(schematic_box(*block))

    # Power path.
    shapes.append(schematic_line(190, 185, 240, 185))
    shapes.append(schematic_line(320, 185, 370, 185))
    shapes.append(schematic_line(470, 185, 530, 145))
    shapes.append(schematic_line(470, 185, 530, 255))
    shapes.append(schematic_line(630, 255, 690, 255))
    shapes.append(schematic_line(820, 255, 850, 255))
    shapes.append(schematic_line(1000, 255, 1060, 255))
    shapes.append(schematic_line(1190, 255, 1230, 255))
    shapes.append(schematic_line(470, 185, 530, 390))
    shapes.append(schematic_line(720, 390, 790, 390))
    shapes.append(schematic_line(470, 185, 990, 390))

    for label, x, y in [
        ("BATT+", 195, 175),
        ("BATT_FUSED", 325, 175),
        ("BAT_SW_12V", 475, 170),
        ("MOTOR_12V", 660, 135),
        ("DCDC_IN_12V", 640, 245),
        ("RK_12V", 1195, 245),
        ("BATT_SENSE", 735, 380),
        ("GND common on all negative pins", 80, 520),
        ("Battery charge port DC5521 stays on battery pack. DO NOT CHARGE HERE.", 80, 550),
        ("DC5525 output to RK3588 is center positive.", 80, 580),
    ]:
        shapes.append(schematic_text(label, x, y))

    return {
        "head": "1~1.11.3~Author`OpenRD`~TRAN`1u`1m`0`{AC`dec``0`0`{DC`0``0`0`{TF```",
        "canvas": "CA~1500~900~#FFFFFF~yes~#CCCCCC~10~1500~900~line~10~pixel~5",
        "shape": shapes,
        "BBox": {"x": 70, "y": 50, "width": 1300, "height": 560},
        "colors": {},
    }


BOM = [
    ["Designator", "Name", "Spec", "Qty", "Note"],
    ["J1", "BATT_IN", "Deans T pigtail pads", "1", "3S battery discharge input"],
    ["J2", "MOTOR_OUT", "Deans T pigtail pads", "1", "to motor driver board"],
    ["F1", "Total fuse", "Automotive blade fuse holder + 10A fuse", "1", "adjust after current test"],
    ["SW1", "Main switch connector", "2P high-current connector", "1", "external switch"],
    ["F2", "RK branch fuse", "5A-7.5A fuse", "1", "adjust after RK load test"],
    ["J3", "DCDC_IN", "2P 5.08mm terminal", "1", "to LTC3780 IN"],
    ["J4", "DCDC_OUT", "2P 5.08mm terminal", "1", "from LTC3780 OUT"],
    ["J5", "RK_OUT", "2P terminal or wire pads", "1", "to DC5525 center-positive plug"],
    ["U1", "DC-DC module", "LTC3780 buck-boost module 78x46mm default", "1", "verify actual hole spacing"],
    ["R1", "Divider high side", "100k 1%", "1", "BATT+ to sense raw"],
    ["R2", "Divider low side", "27k 1%", "1", "sense raw to GND"],
    ["R3", "ADC series resistor", "1k-4.7k", "1", "sense protection"],
    ["J6", "ADC_TEST", "3P 2.54mm header", "1", "BATT_SENSE/GND/NC"],
    ["LED1", "Power LED", "LED", "1", "BAT_SW_12V indicator"],
    ["RLED", "LED resistor", "2.2k-4.7k", "1", "LED current limit"],
    ["H1-H4", "Chassis holes", "M3 3.2mm NPTH", "4", "board mounting"],
    ["U1H1-U1H4", "Module holes", "M3 3.2mm NPTH", "4", "LTC3780 module mounting"],
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)

    schematic_path = OUT / "openrd_pdb_v0_1_schematic.json"
    pcb_path = OUT / "openrd_pdb_v0_1_pcb.json"
    bom_path = OUT / "openrd_pdb_v0_1_bom.csv"
    zip_path = OUT / "openrd_pdb_v0_1_easyeda_std.zip"

    schematic_path.write_text(json.dumps(build_schematic(), ensure_ascii=False, indent=2), encoding="utf-8")
    pcb_path.write_text(json.dumps(build_pcb(), ensure_ascii=False, indent=2), encoding="utf-8")

    with bom_path.open("w", encoding="utf-8", newline="") as fp:
        writer = csv.writer(fp)
        writer.writerows(BOM)

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.write(schematic_path, schematic_path.name)
        zf.write(pcb_path, pcb_path.name)
        zf.write(bom_path, bom_path.name)

    print(f"wrote {schematic_path}")
    print(f"wrote {pcb_path}")
    print(f"wrote {bom_path}")
    print(f"wrote {zip_path}")


if __name__ == "__main__":
    main()
